site_name: geoPythonInfoTree
site_url: https://muratkendir.github.io/geoPythonInfoTree
theme:
    name: material
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
nav:
 - Home : 'index.md'
 - Tables : 
   - 'Geospatial Libraries' : 'geospatial_libraries.md'
   - 'Books' : 'python_books.md'
   - 'Online Resources' : 'python_online_resources.md'
   - 'Editors / IDEs' : 'python_editors.md'
   - 'Interpreters / Implementations' : 'python_interpreters.md'
   - 'SDKs (or APIs)' : 'python_sdks.md'
   - 'Pyhthon GUI Libraries' : 'python_gui_libraries.md'